# Generated by Django 4.2 on 2023-05-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('creador', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PapasFritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paquete', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('Sabor', models.CharField(max_length=200)),
            ],
        ),
    ]
